export const TODOS_LOADING_START = "TODOS_LOADING_START";
export const TODOS_LOADING_SUCCESS = "TODOS_LOADING_SUCCESS";
export const TODOS_LOADING_ERROR = "TODOS_LOADING_ERROR";
export const TODO_CREATE_SUCCESS = "TODO_CREATE_SUCCESS";
export const TODO_UPDATE_SUCCESS = "TODO_UPDATE_SUCCESS";
export const TODO_DELETE_SUCCESS = "TODO_DELETE_SUCCESS";
export const TODOS_CLEAR_ERROR = "TODOS_CLEAR_ERROR";

export const FILTER_SET_SEARCH_TEXT = "FILTER_SET_SEARCH_TEXT";
export const FILTER_TOGGLE_SORT = "FILTER_TOGGLE_SORT";

export const TASK_LOADING_START = "TASK_LOADING_START";
export const TASK_LOADING_SUCCESS = "TASK_LOADING_SUCCESS";
export const TASK_LOADING_ERROR = "TASK_LOADING_ERROR";
export const TASK_SAVE_SUCCESS = "TASK_SAVE_SUCCESS";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_CLEAR_ERROR = "TASK_CLEAR_ERROR";
